//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prometheus.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Prometheus.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap about16 {
            get {
                object obj = ResourceManager.GetObject("about16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap add216 {
            get {
                object obj = ResourceManager.GetObject("add216", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap angel16 {
            get {
                object obj = ResourceManager.GetObject("angel16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap angel24 {
            get {
                object obj = ResourceManager.GetObject("angel24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap angel32 {
            get {
                object obj = ResourceManager.GetObject("angel32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap application_new16 {
            get {
                object obj = ResourceManager.GetObject("application_new16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap application_new32 {
            get {
                object obj = ResourceManager.GetObject("application_new32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap application_ok24 {
            get {
                object obj = ResourceManager.GetObject("application_ok24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap application_ok32 {
            get {
                object obj = ResourceManager.GetObject("application_ok32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap application16 {
            get {
                object obj = ResourceManager.GetObject("application16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap application32 {
            get {
                object obj = ResourceManager.GetObject("application32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrow_left_green16 {
            get {
                object obj = ResourceManager.GetObject("arrow_left_green16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrow_right_green16 {
            get {
                object obj = ResourceManager.GetObject("arrow_right_green16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap book_blue16 {
            get {
                object obj = ResourceManager.GetObject("book_blue16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap book_open16 {
            get {
                object obj = ResourceManager.GetObject("book_open16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap book_open24 {
            get {
                object obj = ResourceManager.GetObject("book_open24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bookmark_add16 {
            get {
                object obj = ResourceManager.GetObject("bookmark_add16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bookmark_add24 {
            get {
                object obj = ResourceManager.GetObject("bookmark_add24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bookmark_down16 {
            get {
                object obj = ResourceManager.GetObject("bookmark_down16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bookmark_up16 {
            get {
                object obj = ResourceManager.GetObject("bookmark_up16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bookmark24 {
            get {
                object obj = ResourceManager.GetObject("bookmark24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bookmark32 {
            get {
                object obj = ResourceManager.GetObject("bookmark32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bookmarks24 {
            get {
                object obj = ResourceManager.GetObject("bookmarks24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap box_software32 {
            get {
                object obj = ResourceManager.GetObject("box_software32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap brush324 {
            get {
                object obj = ResourceManager.GetObject("brush324", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bugmail16 {
            get {
                object obj = ResourceManager.GetObject("bugmail16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bugmail32 {
            get {
                object obj = ResourceManager.GetObject("bugmail32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cabinet16 {
            get {
                object obj = ResourceManager.GetObject("cabinet16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cabinet32 {
            get {
                object obj = ResourceManager.GetObject("cabinet32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap camera232 {
            get {
                object obj = ResourceManager.GetObject("camera232", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cd16 {
            get {
                object obj = ResourceManager.GetObject("cd16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap check16 {
            get {
                object obj = ResourceManager.GetObject("check16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap check216 {
            get {
                object obj = ResourceManager.GetObject("check216", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap checks16 {
            get {
                object obj = ResourceManager.GetObject("checks16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap checks32 {
            get {
                object obj = ResourceManager.GetObject("checks32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap client_network24 {
            get {
                object obj = ResourceManager.GetObject("client_network24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap client_network32 {
            get {
                object obj = ResourceManager.GetObject("client_network32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CollapseTitle {
            get {
                object obj = ResourceManager.GetObject("CollapseTitle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap colors32 {
            get {
                object obj = ResourceManager.GetObject("colors32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap components16 {
            get {
                object obj = ResourceManager.GetObject("components16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap copy16 {
            get {
                object obj = ResourceManager.GetObject("copy16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cube_green16 {
            get {
                object obj = ResourceManager.GetObject("cube_green16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cube_green24 {
            get {
                object obj = ResourceManager.GetObject("cube_green24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cube_molecule_view16 {
            get {
                object obj = ResourceManager.GetObject("cube_molecule_view16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cube_molecule16 {
            get {
                object obj = ResourceManager.GetObject("cube_molecule16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cube_molecule24 {
            get {
                object obj = ResourceManager.GetObject("cube_molecule24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cut16 {
            get {
                object obj = ResourceManager.GetObject("cut16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap data_add16 {
            get {
                object obj = ResourceManager.GetObject("data_add16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap data_copy16 {
            get {
                object obj = ResourceManager.GetObject("data_copy16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap data_delete16 {
            get {
                object obj = ResourceManager.GetObject("data_delete16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap data_deleteall16 {
            get {
                object obj = ResourceManager.GetObject("data_deleteall16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap data_down24 {
            get {
                object obj = ResourceManager.GetObject("data_down24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap data_down32 {
            get {
                object obj = ResourceManager.GetObject("data_down32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap data_new16 {
            get {
                object obj = ResourceManager.GetObject("data_new16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap data_new24 {
            get {
                object obj = ResourceManager.GetObject("data_new24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap data_new32 {
            get {
                object obj = ResourceManager.GetObject("data_new32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap data_view16 {
            get {
                object obj = ResourceManager.GetObject("data_view16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap data_warning32 {
            get {
                object obj = ResourceManager.GetObject("data_warning32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap data16 {
            get {
                object obj = ResourceManager.GetObject("data16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap debug_next16 {
            get {
                object obj = ResourceManager.GetObject("debug_next16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap debug_previous16 {
            get {
                object obj = ResourceManager.GetObject("debug_previous16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap debug_time16 {
            get {
                object obj = ResourceManager.GetObject("debug_time16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap debug_view24 {
            get {
                object obj = ResourceManager.GetObject("debug_view24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap debug24 {
            get {
                object obj = ResourceManager.GetObject("debug24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap debug32 {
            get {
                object obj = ResourceManager.GetObject("debug32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap delete216 {
            get {
                object obj = ResourceManager.GetObject("delete216", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap devil24 {
            get {
                object obj = ResourceManager.GetObject("devil24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap die_gold16 {
            get {
                object obj = ResourceManager.GetObject("die_gold16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap die_gold24 {
            get {
                object obj = ResourceManager.GetObject("die_gold24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap die16 {
            get {
                object obj = ResourceManager.GetObject("die16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap disk_blue16 {
            get {
                object obj = ResourceManager.GetObject("disk_blue16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap disk_blue32 {
            get {
                object obj = ResourceManager.GetObject("disk_blue32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap disks32 {
            get {
                object obj = ResourceManager.GetObject("disks32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document_add16 {
            get {
                object obj = ResourceManager.GetObject("document_add16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document_attachment32 {
            get {
                object obj = ResourceManager.GetObject("document_attachment32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document_edit16 {
            get {
                object obj = ResourceManager.GetObject("document_edit16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document_error16 {
            get {
                object obj = ResourceManager.GetObject("document_error16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document_lock24 {
            get {
                object obj = ResourceManager.GetObject("document_lock24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document_plain_new16 {
            get {
                object obj = ResourceManager.GetObject("document_plain_new16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document_plain_new32 {
            get {
                object obj = ResourceManager.GetObject("document_plain_new32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document_plain16 {
            get {
                object obj = ResourceManager.GetObject("document_plain16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document_text16 {
            get {
                object obj = ResourceManager.GetObject("document_text16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document_time16 {
            get {
                object obj = ResourceManager.GetObject("document_time16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document_up16 {
            get {
                object obj = ResourceManager.GetObject("document_up16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document_view16 {
            get {
                object obj = ResourceManager.GetObject("document_view16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document_warning32 {
            get {
                object obj = ResourceManager.GetObject("document_warning32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document16 {
            get {
                object obj = ResourceManager.GetObject("document16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap earth_view16 {
            get {
                object obj = ResourceManager.GetObject("earth_view16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap earth16 {
            get {
                object obj = ResourceManager.GetObject("earth16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap earth24 {
            get {
                object obj = ResourceManager.GetObject("earth24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap element_down16 {
            get {
                object obj = ResourceManager.GetObject("element_down16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap element_up16 {
            get {
                object obj = ResourceManager.GetObject("element_up16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap element24 {
            get {
                object obj = ResourceManager.GetObject("element24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap environment_view16 {
            get {
                object obj = ResourceManager.GetObject("environment_view16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap environment16 {
            get {
                object obj = ResourceManager.GetObject("environment16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap environment24 {
            get {
                object obj = ResourceManager.GetObject("environment24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap error16 {
            get {
                object obj = ResourceManager.GetObject("error16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap error64 {
            get {
                object obj = ResourceManager.GetObject("error64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap exit16 {
            get {
                object obj = ResourceManager.GetObject("exit16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ExpandTitle {
            get {
                object obj = ResourceManager.GetObject("ExpandTitle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap find_next16 {
            get {
                object obj = ResourceManager.GetObject("find_next16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap find_next24 {
            get {
                object obj = ResourceManager.GetObject("find_next24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap find_previous16 {
            get {
                object obj = ResourceManager.GetObject("find_previous16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap find_text24 {
            get {
                object obj = ResourceManager.GetObject("find_text24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_add16 {
            get {
                object obj = ResourceManager.GetObject("folder_add16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_closed16 {
            get {
                object obj = ResourceManager.GetObject("folder_closed16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_closed32 {
            get {
                object obj = ResourceManager.GetObject("folder_closed32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_edit16 {
            get {
                object obj = ResourceManager.GetObject("folder_edit16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_information16 {
            get {
                object obj = ResourceManager.GetObject("folder_information16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_ok16 {
            get {
                object obj = ResourceManager.GetObject("folder_ok16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_out32 {
            get {
                object obj = ResourceManager.GetObject("folder_out32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder16 {
            get {
                object obj = ResourceManager.GetObject("folder16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap form_blue_new32 {
            get {
                object obj = ResourceManager.GetObject("form_blue_new32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap form_blue16 {
            get {
                object obj = ResourceManager.GetObject("form_blue16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap form_blue32 {
            get {
                object obj = ResourceManager.GetObject("form_blue32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap forward64 {
            get {
                object obj = ResourceManager.GetObject("forward64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap funnel_add24 {
            get {
                object obj = ResourceManager.GetObject("funnel_add24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap funnel_delete16 {
            get {
                object obj = ResourceManager.GetObject("funnel_delete16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap funnel_down16 {
            get {
                object obj = ResourceManager.GetObject("funnel_down16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap funnel_new16 {
            get {
                object obj = ResourceManager.GetObject("funnel_new16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap funnel_preferences16 {
            get {
                object obj = ResourceManager.GetObject("funnel_preferences16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap funnel_up16 {
            get {
                object obj = ResourceManager.GetObject("funnel_up16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap funnel16 {
            get {
                object obj = ResourceManager.GetObject("funnel16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap garbage_empty16 {
            get {
                object obj = ResourceManager.GetObject("garbage_empty16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap garbage_full16 {
            get {
                object obj = ResourceManager.GetObject("garbage_full16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap garbage16 {
            get {
                object obj = ResourceManager.GetObject("garbage16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap gear_run32 {
            get {
                object obj = ResourceManager.GetObject("gear_run32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap gears24 {
            get {
                object obj = ResourceManager.GetObject("gears24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ghost16 {
            get {
                object obj = ResourceManager.GetObject("ghost16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Guerilla24 {
            get {
                object obj = ResourceManager.GetObject("Guerilla24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Guerilla32 {
            get {
                object obj = ResourceManager.GetObject("Guerilla32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap help216 {
            get {
                object obj = ResourceManager.GetObject("help216", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap history16 {
            get {
                object obj = ResourceManager.GetObject("history16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap import216 {
            get {
                object obj = ResourceManager.GetObject("import216", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap index_refresh32 {
            get {
                object obj = ResourceManager.GetObject("index_refresh32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap index24 {
            get {
                object obj = ResourceManager.GetObject("index24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap index32 {
            get {
                object obj = ResourceManager.GetObject("index32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap infomarker {
            get {
                object obj = ResourceManager.GetObject("infomarker", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap information16 {
            get {
                object obj = ResourceManager.GetObject("information16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap information24 {
            get {
                object obj = ResourceManager.GetObject("information24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap joystick16 {
            get {
                object obj = ResourceManager.GetObject("joystick16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap joystick32 {
            get {
                object obj = ResourceManager.GetObject("joystick32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap key116 {
            get {
                object obj = ResourceManager.GetObject("key116", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap keyboard_key16 {
            get {
                object obj = ResourceManager.GetObject("keyboard_key16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lightbulb_on16 {
            get {
                object obj = ResourceManager.GetObject("lightbulb_on16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lightbulb_on24 {
            get {
                object obj = ResourceManager.GetObject("lightbulb_on24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lightbulb_on32 {
            get {
                object obj = ResourceManager.GetObject("lightbulb_on32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lock_open16 {
            get {
                object obj = ResourceManager.GetObject("lock_open16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lock16 {
            get {
                object obj = ResourceManager.GetObject("lock16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap loudspeaker24 {
            get {
                object obj = ResourceManager.GetObject("loudspeaker24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mail_write32 {
            get {
                object obj = ResourceManager.GetObject("mail_write32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap media_pause16 {
            get {
                object obj = ResourceManager.GetObject("media_pause16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap media_play_green16 {
            get {
                object obj = ResourceManager.GetObject("media_play_green16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap media_stop_red16 {
            get {
                object obj = ResourceManager.GetObject("media_stop_red16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap message16 {
            get {
                object obj = ResourceManager.GetObject("message16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap messages24 {
            get {
                object obj = ResourceManager.GetObject("messages24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap modem_earth32 {
            get {
                object obj = ResourceManager.GetObject("modem_earth32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap monitor24 {
            get {
                object obj = ResourceManager.GetObject("monitor24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap monitor32 {
            get {
                object obj = ResourceManager.GetObject("monitor32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap movie24 {
            get {
                object obj = ResourceManager.GetObject("movie24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nav_down_blue16 {
            get {
                object obj = ResourceManager.GetObject("nav_down_blue16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nav_up_blue16 {
            get {
                object obj = ResourceManager.GetObject("nav_up_blue16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap navigate_close16 {
            get {
                object obj = ResourceManager.GetObject("navigate_close16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap navigate_close24 {
            get {
                object obj = ResourceManager.GetObject("navigate_close24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap navigate_cross10 {
            get {
                object obj = ResourceManager.GetObject("navigate_cross10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap navigate_cross16 {
            get {
                object obj = ResourceManager.GetObject("navigate_cross16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap navigate_down16 {
            get {
                object obj = ResourceManager.GetObject("navigate_down16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap navigate_open16 {
            get {
                object obj = ResourceManager.GetObject("navigate_open16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap navigate_open24 {
            get {
                object obj = ResourceManager.GetObject("navigate_open24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap navigate_up16 {
            get {
                object obj = ResourceManager.GetObject("navigate_up16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap news24 {
            get {
                object obj = ResourceManager.GetObject("news24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap note_add16 {
            get {
                object obj = ResourceManager.GetObject("note_add16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap note_delete32 {
            get {
                object obj = ResourceManager.GetObject("note_delete32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap note_edit24 {
            get {
                object obj = ResourceManager.GetObject("note_edit24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap note_edit32 {
            get {
                object obj = ResourceManager.GetObject("note_edit32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap note_new24 {
            get {
                object obj = ResourceManager.GetObject("note_new24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap note_new32 {
            get {
                object obj = ResourceManager.GetObject("note_new32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap note_view24 {
            get {
                object obj = ResourceManager.GetObject("note_view24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap note_view32 {
            get {
                object obj = ResourceManager.GetObject("note_view32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap palette224 {
            get {
                object obj = ResourceManager.GetObject("palette224", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap palette24 {
            get {
                object obj = ResourceManager.GetObject("palette24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap paste16 {
            get {
                object obj = ResourceManager.GetObject("paste16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap paste24 {
            get {
                object obj = ResourceManager.GetObject("paste24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap paste32 {
            get {
                object obj = ResourceManager.GetObject("paste32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pause_button {
            get {
                object obj = ResourceManager.GetObject("pause_button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pill_red16 {
            get {
                object obj = ResourceManager.GetObject("pill_red16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap playingcard24 {
            get {
                object obj = ResourceManager.GetObject("playingcard24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap preferences16 {
            get {
                object obj = ResourceManager.GetObject("preferences16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap preferences24 {
            get {
                object obj = ResourceManager.GetObject("preferences24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap preferences32 {
            get {
                object obj = ResourceManager.GetObject("preferences32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap recycle24 {
            get {
                object obj = ResourceManager.GetObject("recycle24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap recycle32 {
            get {
                object obj = ResourceManager.GetObject("recycle32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap redo16 {
            get {
                object obj = ResourceManager.GetObject("redo16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap refresh16 {
            get {
                object obj = ResourceManager.GetObject("refresh16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap replace216 {
            get {
                object obj = ResourceManager.GetObject("replace216", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap replace24 {
            get {
                object obj = ResourceManager.GetObject("replace24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap row16 {
            get {
                object obj = ResourceManager.GetObject("row16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap safe16 {
            get {
                object obj = ResourceManager.GetObject("safe16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap satellite_dish16 {
            get {
                object obj = ResourceManager.GetObject("satellite_dish16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap satellite_dish24 {
            get {
                object obj = ResourceManager.GetObject("satellite_dish24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap satellite_dish32 {
            get {
                object obj = ResourceManager.GetObject("satellite_dish32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap save_as32 {
            get {
                object obj = ResourceManager.GetObject("save_as32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap scroll16 {
            get {
                object obj = ResourceManager.GetObject("scroll16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap security_agent24 {
            get {
                object obj = ResourceManager.GetObject("security_agent24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap server_client_exchange32 {
            get {
                object obj = ResourceManager.GetObject("server_client_exchange32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap server_from_client32 {
            get {
                object obj = ResourceManager.GetObject("server_from_client32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap server_id_card32 {
            get {
                object obj = ResourceManager.GetObject("server_id_card32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap signpost16 {
            get {
                object obj = ResourceManager.GetObject("signpost16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap stapler16 {
            get {
                object obj = ResourceManager.GetObject("stapler16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap text_align_left16 {
            get {
                object obj = ResourceManager.GetObject("text_align_left16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap text_align_left24 {
            get {
                object obj = ResourceManager.GetObject("text_align_left24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap text_align_right16 {
            get {
                object obj = ResourceManager.GetObject("text_align_right16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap text_code_colored_new32 {
            get {
                object obj = ResourceManager.GetObject("text_code_colored_new32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap text_code_colored16 {
            get {
                object obj = ResourceManager.GetObject("text_code_colored16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap text_code_colored32 {
            get {
                object obj = ResourceManager.GetObject("text_code_colored32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap text_code24 {
            get {
                object obj = ResourceManager.GetObject("text_code24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap text_view16 {
            get {
                object obj = ResourceManager.GetObject("text_view16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap transform216 {
            get {
                object obj = ResourceManager.GetObject("transform216", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap transform224 {
            get {
                object obj = ResourceManager.GetObject("transform224", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap undo16 {
            get {
                object obj = ResourceManager.GetObject("undo16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap undo24 {
            get {
                object obj = ResourceManager.GetObject("undo24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap undo32 {
            get {
                object obj = ResourceManager.GetObject("undo32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap user1_add16 {
            get {
                object obj = ResourceManager.GetObject("user1_add16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap user1_delete16 {
            get {
                object obj = ResourceManager.GetObject("user1_delete16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap user116 {
            get {
                object obj = ResourceManager.GetObject("user116", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap users224 {
            get {
                object obj = ResourceManager.GetObject("users224", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap videocamera16 {
            get {
                object obj = ResourceManager.GetObject("videocamera16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap videocamera24 {
            get {
                object obj = ResourceManager.GetObject("videocamera24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap view16 {
            get {
                object obj = ResourceManager.GetObject("view16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap warning16 {
            get {
                object obj = ResourceManager.GetObject("warning16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap window_earth16 {
            get {
                object obj = ResourceManager.GetObject("window_earth16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap window_earth24 {
            get {
                object obj = ResourceManager.GetObject("window_earth24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap window_earth32 {
            get {
                object obj = ResourceManager.GetObject("window_earth32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap window_environment24 {
            get {
                object obj = ResourceManager.GetObject("window_environment24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap window_sidebar32 {
            get {
                object obj = ResourceManager.GetObject("window_sidebar32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap windows24 {
            get {
                object obj = ResourceManager.GetObject("windows24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wrench24 {
            get {
                object obj = ResourceManager.GetObject("wrench24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap zoom_in16 {
            get {
                object obj = ResourceManager.GetObject("zoom_in16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap zoom_out16 {
            get {
                object obj = ResourceManager.GetObject("zoom_out16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
